language: csharp
solution: ./ZPI.sln
install:
  - sudo apt-get install -y gtk-sharp2
  - nuget restore ./ZPI.sln

script:
  - xbuild ./ZPI.sln
  - nunit-console ./src/SomeLibrary.Tests/bin/Debug/SomeLibrary.Tests.dll
  
 